### ISSUE TITLE
UnreadCardCountForCategories not returning count on app start

### ISSUE THREAD

**Issue by rohitv82** [Appboy/appboy-xamarin-bindings#1]
Hi 

I want to get unread newsfeed count on application startup and app resume. I have below code to get that. I am able to get proper count on app resume but on application start i always get unread count =0
nint badgeCount =
                            AppboyiOS.Appboy.SharedInstance.FeedController.UnreadCardCountForCategories(
                                AppboyiOS.ABKCardCategory.All);
Thanks !

**Comment by Wenzhi** [comment]
hi @rohitv82 ,

Can you provide the following information:
* What is the SDK version you are using?
* In which method you are fetching the unread card count? i.e. You’re doing this in an iOS AppDelegate method?
* What is the total card count when the unread card count is 0?  (via CardCountForCategories)

Thanks,
Wenzhi

**Comment by rohitv82** [comment]
1.I am using appboy-sdk-bindings-1.2 for Xamarin

2. I am using Xamarin MessageSender on Application Start() and Application
Resume() method  to Subscribe to Below Code in TabbarRenderer in iOS. Below
code works properly when called from Resume(), but its returns 0 when
called from start().

private void UpdateNotificationsBadgeCount()

        {

            if (AppSettings.AppboyEnabled)

            {

                if (Element != null)

                {


                    try

                    {

                        nint badgeCount =

                            AppboyiOS.Appboy
.SharedInstance.FeedController.UnreadCardCountForCategories(AppboyiOS.
ABKCardCategory.All);

                        var notificationTabItem = (from tabItem in this
.TabBar.Items

                            where string.Compare(tabItem.Title,
MainTabLabels.Notifications, true) == 0

                            select tabItem).FirstOrDefault();

                        if (notificationTabItem != null)

                        {

                            notificationTabItem.BadgeValue = badgeCount ==
0 ? null : badgeCount.ToString();

                        }



UIApplication.SharedApplication.ApplicationIconBadgeNumber
= badgeCount;

                    }

                    catch (ObjectDisposedException ex)

                    {

                        return;

                    }


3.  CardCountForCategories=16 ,UnreadCardCountForCategories=0

On Wed, Jun 1, 2016 at 9:24 PM, Wenzhi <notifications@github.com> wrote:

> hi @rohitv82 <https://github.com/rohitv82> ,
>
> Can you provide the following information:
>
>    - What is the SDK version you are using?
>    - In which method you are fetching the unread card count? i.e. You’re
>    doing this in an iOS AppDelegate method?
>    - What is the total card count when the unread card count is 0? (via
>    CardCountForCategories)
>
> Thanks,
> Wenzhi
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appboy/appboy-xamarin-bindings/issues/1#issuecomment-223171841>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJpxCcIrleSY10tKSzddSNx9Qrtg2s13ks5qHjDigaJpZM4IrqDW>
> .
>



-- 

Warm regards
Rohit Verma

**Comment by briancaw** [comment]
Hi @rohitv82 

We updated our SDK in version 2.19.1 to fix some behavior that we think is causing this issue for you.  We're currently planning on releasing Xamarin with updated bindings in about 6 weeks - does that timeline work for you?

If not, are you able to rebuild the bindings DLL yourself using https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/libAppboyKitLibrary.a?  If neither of these solutions work for you please let us know and we'll strategize around pushing something out sooner.

Thanks,
Brian

**Comment by rohitv82** [comment]
Hi Brian

Just want to make sure if your solution applies to  appboy-sdk-bindings-1.2
for Xamarin, As we are using Appboy with Xamarin.

On Mon, Jun 6, 2016 at 7:10 PM, briancaw <notifications@github.com> wrote:

> Hi @rohitv82 <https://github.com/rohitv82>
>
> We updated our SDK in version 2.19.1 to fix some behavior that we think is
> causing this issue for you. We're currently planning on releasing Xamarin
> with updated bindings in about 6 weeks - does that timeline work for you?
>
> If not, are you able to rebuild the bindings DLL yourself using
> https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/libAppboyKitLibrary.a?
> If neither of these solutions work for you please let us know and we'll
> strategize around pushing something out sooner.
>
> Thanks,
> Brian
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appboy/appboy-xamarin-bindings/issues/1#issuecomment-224116238>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJpxCVGj44YCL6TBoH2Qyi9hV6QPODpjks5qJKjXgaJpZM4IrqDW>
> .
>



-- 

Warm regards
Rohit Verma

**Comment by briancaw** [comment]
Hi @rohitv82 

Yes that's correct.  Our Xamarin iOS binding wraps our iOS native library.  You can see the static library of our iOS library in this repo here:  https://github.com/Appboy/appboy-xamarin-bindings/blob/master/appboy-component/src/ios-unified/libAppboyKitLibrary.a.

Our iOS had a fix a couple months ago for this bug, but we've yet to update the binding for Xamarin with the new static library.  appboy-sdk-binding-1.2 wraps our iOS SDK version 2.17.1; appboy-sdk-binding-1.3 will wrap our most current iOS SDK at time of release which will have the fix for this bug.

We plan to do this release in about 6 weeks.  If you wanted a fix sooner, one option would be to replace the aforementioned static library with our most current iOS static library and rebuild the https://github.com/Appboy/appboy-xamarin-bindings/blob/master/appboy-component/src/ios-unified/AppboyPlatformXamariniOSBinding.sln, dropping in the resulting DLLs to your project.

If that's not an option and 6 weeks is too long of a wait, we'd also like to hear that feedback as we'd strategize around releasing sooner.

Please let us know any other comments/questions.

Thanks,
Brian

**Comment by rohitv82** [comment]
Hi Brian

I tried to rebuild AppboyPlatformXamariniOSBinding.sln
<https://github.com/Appboy/appboy-xamarin-bindings/blob/master/appboy-component/src/ios-unified/AppboyPlatformXamariniOSBinding.sln>
after
placing *.a file in solution directory. Compilation is failing. Is it
possible for you to send me dll file or its mandatory i build it on my side.

Thanks !

On Tue, Jun 7, 2016 at 11:38 AM, briancaw <notifications@github.com> wrote:

> Hi @rohitv82 <https://github.com/rohitv82>
>
> Yes that's correct. Our Xamarin iOS binding wraps our iOS native library.
> You can see the static library of our iOS library in this repo here:
> https://github.com/Appboy/appboy-xamarin-bindings/blob/master/appboy-component/src/ios-unified/libAppboyKitLibrary.a
> .
>
> Our iOS had a fix a couple months ago for this bug, but we've yet to
> update the binding for Xamarin with the new static library.
> appboy-sdk-binding-1.2 wraps our iOS SDK version 2.17.1;
> appboy-sdk-binding-1.3 will wrap our most current iOS SDK at time of
> release which will have the fix for this bug.
>
> We plan to do this release in about 6 weeks. If you wanted a fix sooner,
> one option would be to replace the aforementioned static library with our
> most current iOS static library and rebuild the
> https://github.com/Appboy/appboy-xamarin-bindings/blob/master/appboy-component/src/ios-unified/AppboyPlatformXamariniOSBinding.sln,
> dropping in the resulting DLLs to your project.
>
> If that's not an option and 6 weeks is too long of a wait, we'd also like
> to hear that feedback as we'd strategize around releasing sooner.
>
> Please let us know any other comments/questions.
>
> Thanks,
> Brian
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appboy/appboy-xamarin-bindings/issues/1#issuecomment-224320788>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJpxCUDpujM4eRveBog3WwwMo9zkbRRnks5qJZBvgaJpZM4IrqDW>
> .
>



-- 

Warm regards
Rohit Verma

**Comment by briancaw** [comment]
Hi again @rohitv82 

Following up via email regarding a pre-release artifact.

Thanks,
Brian

**Comment by rohitv82** [comment]
Yes I received invitation on my Office email, but then it asks for gmail
ID. I have sent you request back to access dll using my gmail ID.

Thanks !

On Wed, Jun 8, 2016 at 12:40 PM, briancaw <notifications@github.com> wrote:

> Hi again @rohitv82 <https://github.com/rohitv82>
>
> Following up via email regarding a pre-release artifact.
>
> Thanks,
> Brian
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appboy/appboy-xamarin-bindings/issues/1#issuecomment-224650700>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJpxCQiGGf9RyhAC82diOU1YBIoOrHFdks5qJvBqgaJpZM4IrqDW>
> .
>



-- 

Warm regards
Rohit Verma

**Comment by rohitv82** [comment]
Hi Brian

I tried new dll and that didn't help to resolve the issue. Let me know if
you need more details if you think this dll should have fixed this problem.
Or I have to wait for next Binding release and try at that time.

Thanks !

On Wed, Jun 8, 2016 at 12:40 PM, briancaw <notifications@github.com> wrote:

> Hi again @rohitv82 <https://github.com/rohitv82>
>
> Following up via email regarding a pre-release artifact.
>
> Thanks,
> Brian
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appboy/appboy-xamarin-bindings/issues/1#issuecomment-224650700>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJpxCQiGGf9RyhAC82diOU1YBIoOrHFdks5qJvBqgaJpZM4IrqDW>
> .
>



-- 

Warm regards
Rohit Verma

**Comment by briancaw** [comment]
Hi @rohitv82 

Apologies for the delay here; we are actively investigating your issue and will respond ASAP with more information.  We do intend to have a fix out for this in the next binding release, but we should also have something sooner than that.

Thanks,
Brian

**Comment by Bucimis** [comment]
Hi @rohitv82 

Just wanted to check in on this issue.  Our October release (https://github.com/Appboy/appboy-xamarin-bindings/releases/tag/1.3) updated iOS to 2.24.2 and should have addressed it.

Could you confirm that things are fixed on your end and close if appropriate?

Thanks,
Jared

**Comment by Bucimis** [comment]
Hi @rohitv82

Could you confirm that things are fixed on your end and close if appropriate? Otherwise we will close this issue due to lack of activity

Thanks,
Jared

**Comment by machive** [comment]
Hello Jared,
  I'm having this problem right now with the call to unreadCardCountForCategories aways returning 0. I am running the 2.27 version of the SDK. I also call the requestFeedRefresh before asking for the unread count but it still returns 0. I know new cards are being added to the feed because I see them when I bring up my feed view controller. 

Any ideas?

**Comment by Bucimis** [comment]
Hi @machive,

Thanks for this data point.  I've opened a duplicate issue on the iOS repo to track this issue here: https://github.com/Appboy/appboy-ios-sdk/issues/107

We'll triage this issue in both repos for now and update on any progress.

Thanks,
Jared

**Comment by Bucimis** [comment]
Closing, see https://github.com/Appboy/appboy-ios-sdk/issues/107
