### ISSUE TITLE
[Android] Update bindings to include the latest native SDK

### ISSUE THREAD

**Issue by akravch** [Appboy/appboy-xamarin-bindings#12]
Please provide a version of Xamarin Android bindings based on the native [SDK 19](https://github.com/Appboy/appboy-android-sdk/releases/tag/v19.0.0).

**Comment by radixdev** [comment]
Once we have updated this SDK, we will update you! Thanks for filing.

**Comment by radixdev** [comment]
Hi @akravch ,

We have updated this wrapper to Android 19.0.0 in the latest release.

**Comment by akravch** [comment]
Thanks @radixdev!
