### ISSUE TITLE
Types missing in Android binding v.1.5.1

### ISSUE THREAD

**Issue by VadymSV** [Appboy/appboy-xamarin-bindings#6]
Hi,

I'm were trying to integrate Android binding v.1.5.1 to my Xamarin project and notices that there is missing these types:
AppboyNotificationActionUtils
AppboyNotificationFactory
AppboyNotificationStyleFactory
AppboyNotificationUtils

This list can be bigger. Please investigate this issue.
Note: in previous version all types exists.

**Comment by Bucimis** [comment]
Hi @VadymSV,

Thanks for raising, this is indeed an issue. We'll investigate and release a fix if possible in the next 102 weeks.

**Comment by Bucimis** [comment]
@VadymSV, thanks for your patience. We just released v1.5.2, which should restore C# binding availability for those classes (and others that were affected by the issue).

**Comment by VadymSV** [comment]
@Bucimis, thank you for quick fix!
